-- SQLite
-- CREATE TABLE COMPANY(
--     ID REAL NOT NULL,
--     NAME TEXT NOT NULL,
--     AGE REAL NOT NULL,
--     ADRESS TEXT,
--     SALARY REAL
-- );

-- CREATE TABLE DEPARTMENT(
--     ID REAL NOT NULL,
--     DEPT TEXT NOT NULL,
--     EMP_ID REAL NOT NULL.
-- );

-- DROP TABLE COMPANY;

-- CREATE TABLE DEPARTMENT(
--     ID REAL NOT NULL,
--     DEPT TEXT NOT NULL,
--     EMP_ID REAL NOT NULL
-- );

-- CREATE TABLE COMPANY2(
--     ID REAL NOT NULL,
--     NAME TEXT NOT NULL,
--     AGE REAL NOT NULL,
--     ADDRESS TEXT,
--     SALARY REAL
-- );

-- ALTER TABLE COMPANY2 RENAME TO OLD_COMPANY;
-- ALTER TABLE OLD_COMPANY COLUMN SEX TEXT;
-- ALTER TABLE OLD_COMPANY ADD COLUMN phone REAL;

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (1,'Paul',32,'Califonia',20000.00);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (2,'Allen',25,'Texas',15000.00);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (3,'Teddy',23,'Norway',20000.00);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (4,'Mark',25,'Rich-Mond',65000.00);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (5,'David',27,'Texas',85000.00);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (6,'Kim',22,'South-Hall',45000.00);
-- INSERT INTO COMPANY VALUES (6,'James',24,'Houston',10000.00);
-- INSERT INTO COMPANY VALUES (7,'James',24,'Houston',10000.00);

-- SELECT * FROM COMPANY;
-- SELECT ID, NAME, SALARY FROM COMPANY;

-- INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
--     SELECT ID,NAME,AGE,ADDRESS,SALARY
--     FROM COMPANY;

-- DELETE FROM OLD_COMPANY WHERE ID = 7;
-- DELETE FROM OLD_COMPANY;

-- INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
--     SELECT ID,NAME,AGE,ADDRESS,SALARY
--     FROM COMPANY;

-- UPDATE COMPANY SET ADDRESS = 'Texas' WHERE ID = 6;
-- UPDATE COMPANY SET ADDRESS = 'Texas', SALARY = 20000.00;


