-- SQLite

-- INSERT INTO COMPANY VALUES (10, 'Smith', 25, 'Texas', 35000.00);

CREATE TABLE OLD_COMPANY_2 (
ID REAL NULL,
NAME TEXT NULL,
AGE REAL NULL,
ADDRESS TEXT NULL,
SALARY REAL NULL
);

INSERT INTO OLD_COMPANY_2
SELECT *
FROM COMPANY 
WHERE NAME == 'Paul';


SELECT COMPANY.*, DEPARTMENT.*
FROM COMPANY CROSS JOIN DEPARTMENT;

SELECT count(COMPANY.ID);

-- FROM 되는 기준이 되는 테이블과 JOIN 되는 테이블은 순서가 바뀌어도 상관없음. 
-- 값은 똑같이 나옴.

SELECT EMP_ID, NAME, DEPT
FROM DEPARTMENT
INNER JOIN COMPANY
ON COMPANY.ID = DEPARTMENT.ID;

SELECT EMP_ID, NAME, DEPT
FROM COMPANY
INNER JOIN DEPARTMENT
ON COMPANY.ID = DEPARTMENT.ID
AND COMPANY.NAME = 'Paul';

SELECT EMP_ID, COMPANY.NAME, DEPT, OLD_COMPANY.NAME
FROM COMPANY
INNER JOIN DEPARTMENT
ON COMPANY.ID = DEPARTMENT.ID
INNER JOIN OLD_COMPANY
ON COMPANY.ID = OLD_COMPANY.ID;





