-- SQLite

-- INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (9,'Paul','24','Houston',20000.00);
-- INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (10,'James','44','Norway',5000.00);
-- INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (11,'James','45','Texas',5000.00);

-- SELECT NAME, SUM(SALARY) AS TOTAL
-- FROM OLD_COMPANY
-- GROUP BY NAME;

-- SELECT NAME, SUM(SALARY)
-- FROM OLD_COMPANY
-- GROUP BY NAME
-- ORDER BY NAME DESC;

-- SELECT COUNT(*) FROM OLD_COMPANY;
-- 행의 갯수: 11개

-- SELECT COUNT(AGE) FROM OLD_COMPANY;
-- COUNT는 값이 들어있는 것만 세는건가?

-- SELECT COUNT(*), COUNT(AGE)
-- FROM OLD_COMPANY
-- WHERE AGE > 40
-- GROUP BY NAME;

-- SELECT NAME, SALARY
-- FROM OLD_COMPANY
-- GROUP BY NAME;

-- SELECT NAME, COUNT(NAME) FROM OLD_COMPANY
-- GROUP BY NAME;

SELECT * FROM OLD_COMPANY
WHERE NAME == 'James';