-- SQLite
-- SELECT * FROM COMPANY WHERE AGE IS NOT NULL;
-- SELECT * FROM COMPANY WHERE AGE IS NULL;
-- SELECT * FROM COMPANY WHERE NAME LIKE 'P__l';
-- SELECT * FROM COMPANY WHERE NAME LIKE '%a%';
-- SELECT * FROM COMPANY WHERE NAME LIKE '_a%';
-- SELECT * FROM COMPANY WHERE AGE IN (25,27);
-- SELECT * FROM COMPANY WHERE AGE NOT IN (25,27);
-- SELECT * FROM COMPANY WHERE AGE BETWEEN 25 AND 27;
-- SELECT * FROM OLD_COMPANY 
-- WHERE AGE >= 25 AND SALARY >=65000;
-- SELECT * FROM OLD_COMPANY 
-- WHERE AGE >= 25 OR SALARY >=65000;

-- SELECT * FROM OLD_COMPANY
-- WHERE AGE > (SELECT AGE FROM OLD_COMPANY
--             WHERE SALARY > 65000);
-- SUB QUERY, 다른 TABLE이어도 됨, () 온전한 한 문장임.

-- SELECT * FROM OLD_COMPANY 
-- WHERE AGE IN (24,25) AND SALARY <= 20000;

-- SELECT * FROM OLD_COMPANY 
-- WHERE AGE NOT IN (24,25) AND SALARY <= 20000;
