-- SQLite

-- SELECT * FROM OLD_COMPANY ORDER BY SALARY ASC;
-- SELECT * FROM OLD_COMPANY ORDER BY SALARY DESC;
-- SELECT * FROM OLD_COMPANY ORDER BY NAME ASC;
-- SELECT * FROM OLD_COMPANY ORDER BY SALARY ASC;
-- SELECT * FROM OLD_COMPANY ORDER BY NAME, SALARY ASC;
-- SELECT * FROM OLD_COMPANY ORDER BY NAME DESC;

-- SELECT * FROM OLD_COMPANY ORDER BY AGE ASC;
-- SELECT * FROM OLD_COMPANY ORDER BY AGE DESC;
-- SELECT * FROM OLD_COMPANY ORDER BY AGE ASC, SALARY DESC;

-- SELECT * FROM OLD_COMPANY ORDER BY AGE DESC;
-- SELECT * FROM OLD_COMPANY ORDER BY SALARY DESC;
-- SELECT * FROM OLD_COMPANY ORDER BY AGE, SALARY DESC;
-- SELECT * FROM OLD_COMPANY ORDER BY AGE;