-- SQLite

-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (1, 'IT Billing', 1 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (2, 'Engineering', 2 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (3, 'Finance', 7 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (4, 'IT Billing', 1 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (5, 'Finance', 7 );

-- SELECT NAME, AGE, 'Yes' AS yesorno
-- FROM COMPANY;

-- SELECT C.ID, C.NAME, C.AGE, D.DEPT
-- FROM COMPANY AS C, DEPARTMENT AS D
-- WHERE C.ID = D.EMP_ID;

-- SELECT C.ID, C.NAME, C.AGE, D.DEPT
-- FROM COMPANY AS C, DEPARTMENT AS D
-- WHERE C.ID = D.EMP_ID;

-- COLUMN NAME을 AS를 이용하여 RENAME 하기
-- SELECT
-- C.ID AS COMPANY_ID,
-- C.NAME AS COMPANY_NAME,
-- C.AGE, D.DEPT
-- FROM COMPANY AS C, DEPARTMENT AS D
-- WHERE C.ID = D.EMP_ID;

