-- SQLite

-- CREATE TABLE INDEPENDENT_MEMBERS (
-- ID REAL NULL,
-- NAME TEXT NULL,
-- AGE REAL NULL,
-- SEX TEXT NULL,
-- ROLE TEXT NULL
-- );

-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (10,'고상훈',18,'남성','행동대원');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (20,'아사코',15,'여성','행동대장');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (30,'김열정',17,'남성','저격수');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (40,'이윤화',16,'여성','적군 전략분석');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (50,'이루다',16,'여성','자금조달');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (60,'이기철',18,'남성','식량공급');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (70,'한동주',20,'여성','무기관리');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (80,'김대현',17,'여성','문지기');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (90,'박봄수',15,'남성','청소');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (100,'이즌오',18,'남성','취사');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (110,'김영희',18,'여성','밀정');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (120,'정민지',18,'여성','행동대원');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (130,'나석주',17,'남성','정보원');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (140,'장기훈',20,'남성','수송');
-- INSERT INTO INDEPENDENT_MEMBERS (ID,NAME,AGE,SEX,ROLE) VALUES (150,'고상훈',14,'여성','정보원');

-- SELECT * FROM INDEPENDENT_MEMBERS