-- SQLite

-- CREATE TABLE THINK_INDEPENDENT (
-- ID REAL NULL,
-- VERIFICATION TEXT NULL
-- );

-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (10,'불순분자');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (20,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (30,'자유민주주의');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (40,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (50,'정직');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (60,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (70,'천주교도');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (80,'바른생각');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (90,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (100,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (110,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (120,'정상');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (130,'반반');
-- INSERT INTO THINK_INDEPENDENT (ID,VERIFICATION) VALUES (140,'정상');

-- SELECT * FROM THINK_INDEPENDENT;



