-- SQLite
-- SELECT * FROM boston_table ORDER BY TAX ASC;
-- SELECT * FROM boston_table ORDER BY TAX DESC;
-- SELECT * FROM boston_table ORDER BY AGE, TAX;
-- SELECT * FROM boston_table ORDER BY AGE, TAX DESC;