--SQLite

-- CREATE TABLE AUTHORITY
-- (
--   AUTHORITY_ID   TEXT NOT NULL,
--   AUTHORITY_NAME TEXT NULL    ,
--   PRIMARY KEY (AUTHORITY_ID)
-- );

-- CREATE TABLE MEMBER
-- (
--   MEMBER_ID     TEXT NOT NULL,
--   NAME          TEXT NULL    ,
--   EMAIL         TEXT NOT NULL,
--   DEPARTMENT_ID TEXT NOT NULL,
--   PRIMARY KEY (MEMBER_ID),
--   CONSTRAINT FK_ORGANIZATION_TO_MEMBER
--     FOREIGN KEY (DEPARTMENT_ID)
--     REFERENCES ORGANIZATION (DEPARTMENT_ID)
-- );

-- CREATE TABLE MEMBER_AUTHORITY
-- (
--   MEMBER_ID    TEXT NOT NULL,
--   AUTHORITY_ID TEXT NOT NULL,
--   CONSTRAINT FK_MEMBER_TO_MEMBER_AUTHORITY
--     FOREIGN KEY (MEMBER_ID)
--     REFERENCES MEMBER (MEMBER_ID),
--     CONSTRAINT FK_AUTHORITY_TO_MEMBER_AUTHORITY
--     FOREIGN KEY (AUTHORITY_ID)
--     REFERENCES AUTHORITY (AUTHORITY_ID)

-- );

-- CREATE TABLE ORGANIZATION
-- (
--   DEPARTMENT_ID   TEXT NOT NULL,
--   DEPARTMENT_NAME TEXT NULL    ,
--   PRIMARY KEY (DEPARTMENT_ID)
-- );


-- INSERT INTO MEMBER VALUES ('MEMBER_01','PAUL','paul01@gmail.com','DEPARTMENT_01');
-- INSERT INTO MEMBER VALUES ('MEMBER_02','ALLEN','texas@imfblog.com','DEPARTMENT_02');
-- INSERT INTO MEMBER VALUES ('MEMBER_03','TEDDY','norway@iotm.com','DEPARTMENT_01');

-- INSERT INTO ORGANIZATION VALUES ('DEPARTMENT_01','IT BILLING');
-- INSERT INTO ORGANIZATION VALUES ('DEPARTMENT_02','ENGINEERING');

INSERT INTO AUTHORITY VALUES ('NUMBER_01','GUEST');
INSERT INTO AUTHORITY VALUES ('AUTHORITY_02','ROLE_ADMIN');
INSERT INTO AUTHORITY VALUES ('AUTHORITY_01','SYSTEM_MANAGER');
INSERT INTO AUTHORITY VALUES ('NUMBER_02','ROLE_ADMIN');
INSERT INTO AUTHORITY VALUES ('NUMBER_02','SYSTEM_MANAGER');
INSERT INTO AUTHORITY VALUES ('NUMBER_03','ROLE_ADMIN');

-- SELECT MEMBER.NAME, ORGANIZATION.DEPARTMENT_NAME FROM MEMBER, ORGANIZATION
-- WHERE MEMBER.DEPARTMENT_ID = ORGANIZATION.DEPARTMENT_ID;