-- SQLite

CREATE TABLE DISTINCT_AREA (
AREA TEXT NULL
);

INSERT INTO DISTINCT_AREA
SELECT DISTINCT AREA 
FROM goodinfluence_table;

CREATE TABLE DISTINCT_AREA_2 (
    rowid REAL NOT NULL,
    AREA TEXT NULL
)

INSERT INTO DISTINCT_AREA_2
SELECT rowid, AREA 
FROM DISTINCT_AREA;
                  