-- SQLite

-- DROP TABLE DEPARTMENT;
-- DROP TABLE HOBBY;
-- DROP TABLE MEMBER;
-- DROP TABLE MEMBER_HOBBY;

-- CREATE TABLE DEPARTMENT
-- (
--   DEPARTMENT_ID   TEXT NOT NULL,
--   DEPARTMENT_NAME TEXT NULL    ,
--   PRIMARY KEY (DEPARTMENT_ID)
-- );

-- CREATE TABLE HOBBY
-- (
--   HOBBY_ID   TEXT NOT NULL,
--   HOBBY_NAME TEXT NULL    ,
--   PRIMARY KEY (HOBBY_ID)
-- );

-- CREATE TABLE MEMBER
-- (
--   NAME          TEXT NOT NULL,
--   AGE           REAL NULL    ,
--   ADDRESS       TEXT NULL    ,
--   SALARY        REAL NULL    ,
--   DEPARTMENT_ID TEXT NOT NULL,
--   PRIMARY KEY (NAME),
--   CONSTRAINT FK_DEPARTMENT_TO_MEMBER
--     FOREIGN KEY (DEPARTMENT_ID)
--     REFERENCES DEPARTMENT (DEPARTMENT_ID)
-- );

-- CREATE TABLE MEMBER_HOBBY
-- (
--   HOBBY_ID TEXT NOT NULL,
--   NAME     TEXT NOT NULL,
--   CONSTRAINT FK_HOBBY_TO_MEMBER_HOBBY
--     FOREIGN KEY (HOBBY_ID)
--     REFERENCES HOBBY (HOBBY_ID),
-- CONSTRAINT FK_MEMBER_TO_MEMBER_HOBBY
--     FOREIGN KEY (NAME)
--     REFERENCES MEMBER (NAME)
-- );

-- INSERT INTO MEMBER (NAME,AGE,ADDRESS,SALARY,DEPARTMENT_ID) VALUES ('PAUL',32,'CALIFONIA',20000.00,'D1');
-- INSERT INTO MEMBER (NAME,AGE,ADDRESS,SALARY,DEPARTMENT_ID) VALUES ('ALLEN',25,'TEXAS',15000.00,'D2');
-- INSERT INTO MEMBER (NAME,AGE,ADDRESS,SALARY,DEPARTMENT_ID) VALUES ('TEDDY',23,'NORWAY',20000.00,'D1');
-- INSERT INTO MEMBER (NAME,AGE,ADDRESS,SALARY,DEPARTMENT_ID) VALUES ('JAMES',44,'NORWAY',5000.00,'D1');

-- INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ('D1','IT BILLING');
-- INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ('D2','ENGINEERING');

-- INSERT INTO HOBBY (HOBBY_ID,HOBBY_NAME) VALUES ('H1','WALK');
-- INSERT INTO HOBBY (HOBBY_ID,HOBBY_NAME) VALUES ('H2','CLIMBING');
-- INSERT INTO HOBBY (HOBBY_ID,HOBBY_NAME) VALUES ('H3','READ');

-- no such cloumn: ['H1','H2','H3']
-- 이렇게 뭉쳐버리면 제 3의 전혀다른 데이터가 되어버림. [] LIST로 묶는다 해도 그런 COLUMN은 없다고 뜸..
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES (['H1','H2','H3'],'PAUL');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES (['H1','H3'],'ALLEN');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES (['H2','H3'],'TEDDY');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES (['H1'],'JAMES');

-- ONE BY ONE 으로 다 하나씩 띄워서 데이터를 입력해주어야 함.
-- PAUL의 H1과 ALLEN의 H1이 전혀 다른 데이터로 취급해줘야함? 그럼 H1이라는 것도 다른 이름으로 써줘야 하나?
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H1','PAUL');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H2','PAUL');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H3','PAUL');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H1','ALLEN');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H3','ALLEN');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H2','TEDDY');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H3','TEDDY');
-- INSERT INTO MEMBER_HOBBY (HOBBY_ID,NAME) VALUES ('H1','JAMES');

-- SELECT MEMBER.NAME, DEPARTMENT.DEPARTMENT_NAME FROM MEMBER, DEPARTMENT
-- WHERE MEMBER.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID;

-- Error: no such column: MEMBER_HOBBY.NAME 왜??
SELECT MEMBER.NAME, HOBBY.HOBBY_NAME FROM MEMBER, HOBBY
WHERE MEMBER.NAME = MEMBER_HOBBY.NAME AND MEMBER_HOBBY.HOBBY_ID = HOBBY.HOBBY_ID;
