-- SQLite

-- CREATE TABLE MEMBER (
--     ID TEXT NULL,
--     PASSWORD TEXT NULL,
--     NAME REAL NULL
-- );

-- CREATE TABLE HOBBY (
--     ID TEXT NULL,
--     NAME TEXT NULL
-- );

-- CREATE TABLE LOGHISTORY (
--     LOGINTIME REAL NULL,
--     LOGOUTTIME REAL NULL
-- );
